import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#b9b6b8ff',
    paddingHorizontal: 20,
  },  
  card: {
    width: '40%',
    marginBottom: 25,
    alignItems: 'center',
  },
  scrollContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  maintitle: {
    fontSize: 36,
    textAlign: 'center',
    marginTop: 10,
    fontWeight: '400',
  },
    title: {
    fontSize: 36,
    textAlign: 'center',
    marginTop: 30,
    marginBottom: 30,
    fontWeight: '400',
  },
  menuBox: {
    flex: 1,
    width: "90%",
    marginTop: 30,
    marginBottom: 80,
    marginLeft: 20,
    marginRight: 20,
    maxHeight: "55%",
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#000',
    padding: 10,
  },
  drinksBox: {
    flex: 1,
    marginTop: 30,
    marginBottom: 30,
    marginLeft: 15,
    marginRight: 15,
    maxHeight: 500,
    borderWidth: 1,
    borderRadius: 4,    
    borderColor: '#000',
    padding: 10,
  },
  editmenuBox: {
    flex: 1,
    marginTop: 30,
    marginBottom: 50,
    marginLeft: 25,
    marginRight: 25,
    maxHeight: 700,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#000',
    padding: 15,
  },
  item: {
    alignItems: 'center',
    marginBottom: 20,
  },
    mainitem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  populateButton: {
    backgroundColor: "#8d8d8dff",
    paddingVertical: 13,
    paddingHorizontal: 40,
    borderRadius: 30,
    right: 15,
  },
  clearButton: {
    backgroundColor: "#8d8d8dff",
    paddingVertical: 13,
    paddingHorizontal: 40,
    borderRadius: 30,
    left: 10,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "center",
    width: "90%",
    marginTop: 2,
    alignItems: 'center',
    left: 20,
  },
  itemName: {
    fontWeight: 'bold',
    fontSize: 14,
    alignItems: 'center',
  },
  itemDesc: {
    color: '#fffdfdff',
    fontSize: 11,
    marginTop: 4,
    width: '90%',
  },
  itemPrice: {
    fontWeight: '600',
    fontSize: 14,
    width: 80,
    textAlign: 'right',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 30, // gives some space between images
    width: '100%',
  },
  image: {
    width: 170,
    height: 170,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#000',
  },
  label: {
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 8,
  },
  form: {
    marginBottom: 40,
  },
  input: {
    backgroundColor: '#d9d7d8',
    borderWidth: 1,
    borderColor: '#000',
    padding: 5,
    fontSize: 16,
    marginBottom: 10,
  },
  counter: {
    position: "absolute",
    top: 600,
    right: 21,
    fontSize: 18,
    fontWeight: "600",
  },
  triggerContainer: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  backgroundColor: '#222',
  paddingVertical: 10,
},
triggerBtn: {
  backgroundColor: '#007AFF',
  paddingVertical: 10,
  paddingHorizontal: 20,
  borderRadius: 10,
},
triggerText: {
  color: '#fff',
  fontWeight: 'bold',
  fontSize: 16,
},
popupContainer: {
  position: 'absolute',
  top: 70,
  left: 0,
  right: 0,
  alignItems: 'center',
},
popupText: {
  backgroundColor: '#007AFF',
  color: '#fff',
  paddingVertical: 10,
  paddingHorizontal: 20,
  borderRadius: 20,
  fontWeight: '600',
  shadowColor: '#000',
  shadowOpacity: 0.3,
  shadowRadius: 4,
  elevation: 5,
},
pickerContainer: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    marginVertical: 8,
    overflow: 'hidden', // ensures dropdown doesn’t exceed boundaries
    backgroundColor: '#fff',
  },
  picker: {
    height: 50,
    width: '100%',
  },
  addButton: {
    backgroundColor: "#8d8d8dff", 
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 25,
    marginTop: 12,
    alignSelf: 'center',
  },    
  button: {
    alignSelf: 'center',
    backgroundColor: "#8d8d8dff",
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 25,
    marginTop: -20
  },
    subbutton: {
    alignSelf: 'center',
    backgroundColor: "#8d8d8dff",
    paddingHorizontal: 40,
    paddingVertical: 10,
    borderRadius: 25,
    marginBottom: 40,
  },
  buttonText: {
    fontWeight: '600',
    fontSize: 18,
  },
  indexposition:{
    marginTop: 30,
    marginBottom: 121,
    flex: 1,
    backgroundColor: '#d9d7d8',
    paddingHorizontal: 20,
  },
    menuItem: { 
      marginBottom: 15, 
      padding: 10, 
      borderRadius: 8, 
      backgroundColor: '#f2f2f2' 
  },
  navBar: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: '#d9d7d8',
    paddingVertical: 7,
    borderTopWidth: 1,
    borderTopColor: '#aaa',
    alignItems: 'center',
  },
    tabBar: {
    backgroundColor: '#b6b6b6ff',
    borderTopWidth: 0,
    elevation: 15,
    height: 65,
    paddingBottom: 5,
  },
  avgPriceText: {
    fontSize: 12,
    fontWeight: '500',
    marginTop: -132,
    textAlign: 'left',
    marginLeft: 25
  },
});